2024-06-25 17:04:42.049 | INFO | Common.logger:wrapper:43 | 函数 test_login_onelap 开始执行，入参:(){}
2024-06-25 17:04:47.361 | INFO | test_login:test_login_onelap:14 | 连接设备成功
2024-06-25 17:04:57.416 | ERROR | Common.logger:wrapper:53 | 函数 test_login_onelap 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_login.py", line 17, in test_login_onelap
    find_element_wrap(driver, 'id', 'com.onelap.bls.dear:id/btn_login_index').click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\Common\find_element.py", line 10, in find_element_wrap
    raise e
  File "F:\python_project\appium_project\Common\find_element.py", line 7, in find_element_wrap
    element = WebDriverWait(driver, 10, 0.25).until(ec.visibility_of_element_located((find_type, find_key)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
    at AndroidUiautomator2Driver.findElement (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)


2024-06-25 17:05:18.470 | INFO | Common.logger:wrapper:43 | 函数 test_login_onelap 开始执行，入参:(){}
2024-06-25 17:05:22.322 | INFO | test_login:test_login_onelap:14 | 连接设备成功
2024-06-25 17:05:29.111 | INFO | test_login:test_login_onelap:25 | 登录完成
2024-06-25 17:05:41.148 | ERROR | Common.logger:wrapper:53 | 函数 test_login_onelap 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_login.py", line 28, in test_login_onelap
    get_app_name = find_element_wrap(driver, 'id', 'com.onelap.bls.dear:id/tv_app_name_main_fragment')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\Common\find_element.py", line 10, in find_element_wrap
    raise e
  File "F:\python_project\appium_project\Common\find_element.py", line 7, in find_element_wrap
    element = WebDriverWait(driver, 10, 0.25).until(ec.visibility_of_element_located((find_type, find_key)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
    at AndroidUiautomator2Driver.findElement (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)


2024-06-25 17:06:12.943 | INFO | Common.logger:wrapper:43 | 函数 test_login_onelap 开始执行，入参:(){}
2024-06-25 17:06:18.099 | INFO | test_login:test_login_onelap:14 | 连接设备成功
2024-06-25 17:06:27.940 | INFO | test_login:test_login_onelap:25 | 登录完成
2024-06-25 17:06:42.079 | ERROR | Common.logger:wrapper:53 | 函数 test_login_onelap 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_login.py", line 30, in test_login_onelap
    safe_dialog = find_element_wrap(driver, 'id', 'com.onelap.bls.dear:id/tv_confirm_common_dialog').click()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\Common\find_element.py", line 10, in find_element_wrap
    raise e
  File "F:\python_project\appium_project\Common\find_element.py", line 7, in find_element_wrap
    element = WebDriverWait(driver, 10, 0.25).until(ec.visibility_of_element_located((find_type, find_key)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
    at AndroidUiautomator2Driver.findElement (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)


2024-06-25 17:07:25.830 | INFO | Common.logger:wrapper:43 | 函数 test_login_onelap 开始执行，入参:(){}
2024-06-25 17:07:30.974 | INFO | test_login:test_login_onelap:14 | 连接设备成功
2024-06-25 17:07:41.482 | INFO | test_login:test_login_onelap:25 | 登录完成
2024-06-25 17:07:55.861 | INFO | Common.logger:wrapper:43 | 函数 test_login_onelap 开始执行，入参:(){}
2024-06-25 17:08:00.915 | INFO | test_login:test_login_onelap:14 | 连接设备成功
2024-06-25 17:08:13.331 | INFO | test_login:test_login_onelap:25 | 登录完成
2024-06-25 17:08:15.938 | INFO | test_login:test_login_onelap:32 | home_app_name断言成功
2024-06-25 17:08:15.938 | INFO | Common.logger:wrapper:48 | 函数 test_login_onelap 执行完成，函数返回结果：None

2024-06-25 17:10:33.763 | INFO | Common.logger:wrapper:43 | 函数 test_login_onelap 开始执行，入参:(){}
2024-06-25 17:10:37.832 | INFO | test_login:test_login_onelap:14 | 连接设备成功
2024-06-25 17:10:47.352 | INFO | test_login:test_login_onelap:25 | 登录完成
2024-06-25 17:10:50.110 | INFO | test_login:test_login_onelap:32 | home_app_name断言成功
2024-06-25 17:10:50.110 | INFO | Common.logger:wrapper:48 | 函数 test_login_onelap 执行完成，函数返回结果：None

2024-06-25 17:11:21.799 | INFO | Common.logger:wrapper:43 | 函数 test_login_onelap 开始执行，入参:(){}
2024-06-25 17:11:27.012 | INFO | TestCase.test_login:test_login_onelap:14 | 连接设备成功
2024-06-25 17:11:37.629 | INFO | TestCase.test_login:test_login_onelap:25 | 登录完成
2024-06-25 17:11:40.205 | INFO | TestCase.test_login:test_login_onelap:32 | home_app_name断言成功
2024-06-25 17:11:40.205 | INFO | Common.logger:wrapper:48 | 函数 test_login_onelap 执行完成，函数返回结果：None

2024-06-25 17:12:42.987 | INFO | TestCase.conftest:login_onelap:17 | 连接设备成功
2024-06-25 17:14:21.780 | INFO | TestCase.conftest:login_onelap:17 | 连接设备成功
2024-06-25 17:14:30.985 | INFO | TestCase.conftest:login_onelap:28 | 登录完成
2024-06-25 17:14:36.707 | INFO | TestCase.conftest:login_onelap:35 | home_app_name断言成功
2024-06-25 17:14:36.708 | INFO | Common.logger:wrapper:43 | 函数 test_report 开始执行，入参:(<TestCase.test_onelap_report.TestOnelap object at 0x000001AA41CE1520>,){'login_onelap': None}
2024-06-25 17:15:08.827 | INFO | TestCase.conftest:login_onelap:17 | 连接设备成功
2024-06-25 17:15:18.545 | INFO | TestCase.conftest:login_onelap:28 | 登录完成
2024-06-25 17:15:21.809 | INFO | TestCase.conftest:login_onelap:35 | home_app_name断言成功
2024-06-25 17:15:21.810 | INFO | Common.logger:wrapper:43 | 函数 test_report 开始执行，入参:(<TestCase.test_onelap_report.TestOnelap object at 0x000001B4A47EEAE0>,){'login_onelap': None}
2024-06-25 17:15:35.799 | ERROR | Common.logger:wrapper:53 | 函数 test_report 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_onelap_report.py", line 19, in test_report
    find_element_wrap(driver, 'id', "com.android.packageinstaller:id/permission_allow_button").click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\Common\find_element.py", line 10, in find_element_wrap
    raise e
  File "F:\python_project\appium_project\Common\find_element.py", line 7, in find_element_wrap
    element = WebDriverWait(driver, 10, 0.25).until(ec.visibility_of_element_located((find_type, find_key)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
    at AndroidUiautomator2Driver.findElement (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)


2024-06-25 17:16:28.124 | INFO | TestCase.conftest:login_onelap:17 | 连接设备成功
2024-06-25 17:17:12.067 | INFO | TestCase.conftest:login_onelap:17 | 连接设备成功
2024-06-25 17:17:26.629 | INFO | TestCase.conftest:login_onelap:28 | 登录完成
2024-06-25 17:17:30.983 | INFO | TestCase.conftest:login_onelap:35 | home_app_name断言成功
2024-06-25 17:17:30.985 | INFO | Common.logger:wrapper:43 | 函数 test_report 开始执行，入参:(<TestCase.test_onelap_report.TestOnelap object at 0x000001F535095EB0>,){'login_onelap': None}
2024-06-25 17:17:46.456 | ERROR | Common.logger:wrapper:53 | 函数 test_report 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_onelap_report.py", line 21, in test_report
    find_element_wrap(driver, 'id', "com.onelap.bls.dear:id/include_planet_bottom_navigation").click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\Common\find_element.py", line 10, in find_element_wrap
    raise e
  File "F:\python_project\appium_project\Common\find_element.py", line 7, in find_element_wrap
    element = WebDriverWait(driver, 10, 0.25).until(ec.visibility_of_element_located((find_type, find_key)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
NoSuchElementError: An element could not be located on the page using the given search parameters.
    at AndroidUiautomator2Driver.findElOrEls (C:\Users\Administrator\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-android-driver\lib\commands\find.ts:86:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AndroidUiautomator2Driver.findElOrElsWithProcessing (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:60:12)
    at AndroidUiautomator2Driver.findElement (C:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\basedriver\commands\find.ts:75:12)


2024-06-25 17:19:47.998 | INFO | TestCase.conftest:login_onelap:17 | 连接设备成功
2024-06-25 17:19:59.181 | INFO | TestCase.conftest:login_onelap:28 | 登录完成
2024-06-25 17:20:07.156 | INFO | TestCase.conftest:login_onelap:35 | home_app_name断言成功
2024-06-25 17:20:07.158 | INFO | Common.logger:wrapper:43 | 函数 test_report 开始执行，入参:(<TestCase.test_onelap_report.TestOnelap object at 0x000001E413626780>,){'login_onelap': None}
2024-06-25 17:20:33.823 | INFO | Common.logger:wrapper:48 | 函数 test_report 执行完成，函数返回结果：None

2024-06-25 18:48:18.062 | INFO | Common.logger:wrapper:43 | 函数 test_report_boss 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x00000157330712B0>,){}
2024-06-25 18:48:24.708 | ERROR | Common.logger:wrapper:53 | 函数 test_report_boss 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_boss_report.py", line 71, in test_report_boss
    response = requests.post(url, headers=headers, data=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_headers(headers)
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\models.py", line 490, in prepare_headers
    check_header_validity(header)
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\utils.py", line 1042, in check_header_validity
    _validate_header_part(header, value, 1)
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\utils.py", line 1051, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Header part ({'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiJkaXN0cmljdF9yZWxlYXNlIiwiaXNzIjoyMzg0OTIsInBsYXRmb3JtIjowLCJuYmYiOjE3MTkzMTI0NDYsImV4cCI6MTcxOTM5ODkwNn0.p6GAzWHUCdOrlKEvM8KzVqX6nkEkqEWNz6GXAv93vM8'}) from ('Authorization', {'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiJkaXN0cmljdF9yZWxlYXNlIiwiaXNzIjoyMzg0OTIsInBsYXRmb3JtIjowLCJuYmYiOjE3MTkzMTI0NDYsImV4cCI6MTcxOTM5ODkwNn0.p6GAzWHUCdOrlKEvM8KzVqX6nkEkqEWNz6GXAv93vM8'}) must be of type str or bytes, not <class 'set'>


2024-06-25 18:49:14.411 | INFO | Common.logger:wrapper:43 | 函数 test_report_boss 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x000001FBA5785EE0>,){}
2024-06-25 18:49:20.000 | ERROR | Common.logger:wrapper:53 | 函数 test_report_boss 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_boss_report.py", line 71, in test_report_boss
    response = requests.post(url, headers=headers, data=data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\sessions.py", line 484, in prepare_request
    p.prepare(
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\models.py", line 368, in prepare
    self.prepare_headers(headers)
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\models.py", line 490, in prepare_headers
    check_header_validity(header)
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\utils.py", line 1042, in check_header_validity
    _validate_header_part(header, value, 1)
  File "F:\python_project\appium_project\.venv\Lib\site-packages\requests\utils.py", line 1051, in _validate_header_part
    raise InvalidHeader(
requests.exceptions.InvalidHeader: Header part ({'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiJkaXN0cmljdF9yZWxlYXNlIiwiaXNzIjoyMzg0OTIsInBsYXRmb3JtIjowLCJuYmYiOjE3MTkzMTI1MDIsImV4cCI6MTcxOTM5ODk2Mn0.kwfqstHOxxwGPqzkC9-L6B5ktVBrMlsHqrRPzwgH3GE'}) from ('Authorization', {'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJrZXkiOiJkaXN0cmljdF9yZWxlYXNlIiwiaXNzIjoyMzg0OTIsInBsYXRmb3JtIjowLCJuYmYiOjE3MTkzMTI1MDIsImV4cCI6MTcxOTM5ODk2Mn0.kwfqstHOxxwGPqzkC9-L6B5ktVBrMlsHqrRPzwgH3GE'}) must be of type str or bytes, not <class 'set'>


2024-06-25 18:50:59.976 | INFO | Common.logger:wrapper:43 | 函数 test_report_boss 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x00000270F81D5220>,){}
2024-06-25 18:51:06.707 | INFO | TestCase.test_boss_report:test_report_boss:73 | 添加举报数据成功
2024-06-25 18:51:10.912 | INFO | Common.logger:wrapper:48 | 函数 test_report_boss 执行完成，函数返回结果：None

2024-06-25 18:53:18.208 | INFO | Common.logger:wrapper:43 | 函数 test_report_boss 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x00000294CACA16D0>,){}
2024-06-25 18:53:25.418 | INFO | TestCase.test_boss_report:test_report_boss:73 | 添加举报数据成功
2024-06-25 18:53:29.968 | ERROR | Common.logger:wrapper:53 | 函数 test_report_boss 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_boss_report.py", line 112, in test_report_boss
    audit_status = table.find_element(By.XPATH, '//*[@class="table table-hover grid-table"]/tbody/tr/td[12]').text
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 417, in find_element
    return self._execute(Command.FIND_CHILD_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=126.0.6478.115); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF7400D3E52+31618]
	(No symbol) [0x00007FF74004B0B9]
	(No symbol) [0x00007FF73FF0888A]
	(No symbol) [0x00007FF73FF1AF2D]
	(No symbol) [0x00007FF73FF1B9BA]
	(No symbol) [0x00007FF73FF0F71B]
	(No symbol) [0x00007FF73FF0D486]
	(No symbol) [0x00007FF73FF11011]
	(No symbol) [0x00007FF73FF110B0]
	(No symbol) [0x00007FF73FF5805C]
	(No symbol) [0x00007FF73FF5862C]
	(No symbol) [0x00007FF73FF4BCDC]
	(No symbol) [0x00007FF73FF7D14F]
	(No symbol) [0x00007FF73FF4BBA6]
	(No symbol) [0x00007FF73FF7D320]
	(No symbol) [0x00007FF73FF9CA80]
	(No symbol) [0x00007FF73FF7CEB3]
	(No symbol) [0x00007FF73FF4A46B]
	(No symbol) [0x00007FF73FF4B001]
	GetHandleVerifier [0x00007FF7403DA02D+3202397]
	GetHandleVerifier [0x00007FF740426A4D+3516285]
	GetHandleVerifier [0x00007FF74041C4C0+3473904]
	GetHandleVerifier [0x00007FF740185D56+760454]
	(No symbol) [0x00007FF740056B5F]
	(No symbol) [0x00007FF740051CF4]
	(No symbol) [0x00007FF740051E82]
	(No symbol) [0x00007FF74004122F]
	BaseThreadInitThunk [0x00007FFFD70C257D+29]
	RtlUserThreadStart [0x00007FFFD7FCAA58+40]



2024-06-25 18:54:33.803 | INFO | Common.logger:wrapper:43 | 函数 test_report_boss 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x0000018671D254F0>,){}
2024-06-25 18:54:40.404 | INFO | TestCase.test_boss_report:test_report_boss:73 | 添加举报数据成功
2024-06-25 18:54:45.022 | INFO | Common.logger:wrapper:48 | 函数 test_report_boss 执行完成，函数返回结果：None

2024-06-25 19:15:56.597 | INFO | TestCase.conftest:add_report_requests:79 | 添加举报数据成功
2024-06-25 19:17:32.944 | INFO | TestCase.conftest:add_report_requests:77 | 添加举报数据成功
2024-06-25 19:17:32.945 | INFO | Common.logger:wrapper:43 | 函数 test_boss_report_pass_notice 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x000001C9F5B77470>,){'add_report_requests': 124}
2024-06-25 19:17:37.388 | INFO | Common.logger:wrapper:48 | 函数 test_boss_report_pass_notice 执行完成，函数返回结果：None

2024-06-25 19:28:13.688 | INFO | TestCase.conftest:add_report_requests:77 | 添加举报数据成功
2024-06-25 19:28:13.689 | INFO | Common.logger:wrapper:43 | 函数 test_boss_report_pass_notice 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x000001C4EA16D940>,){'add_report_requests': 125}
2024-06-25 19:28:17.492 | ERROR | Common.logger:wrapper:53 | 函数 test_boss_report_pass_notice 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_boss_report.py", line 144, in test_boss_report_pass_notice
    driver.switch_to.alert.accept()
    ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\switch_to.py", line 58, in alert
    _ = alert.text
        ^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\common\alert.py", line 58, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoAlertPresentException: Message: no such alert
  (Session info: chrome=126.0.6478.115)
Stacktrace:
	GetHandleVerifier [0x00007FF7400D3E52+31618]
	(No symbol) [0x00007FF74004B0B9]
	(No symbol) [0x00007FF73FF086B9]
	(No symbol) [0x00007FF73FEF8237]
	(No symbol) [0x00007FF73FF2BEEF]
	(No symbol) [0x00007FF73FF7D1BD]
	(No symbol) [0x00007FF73FF2BD6B]
	(No symbol) [0x00007FF73FF7CEB3]
	(No symbol) [0x00007FF73FF4A46B]
	(No symbol) [0x00007FF73FF4B001]
	GetHandleVerifier [0x00007FF7403DA02D+3202397]
	GetHandleVerifier [0x00007FF740426A4D+3516285]
	GetHandleVerifier [0x00007FF74041C4C0+3473904]
	GetHandleVerifier [0x00007FF740185D56+760454]
	(No symbol) [0x00007FF740056B5F]
	(No symbol) [0x00007FF740051CF4]
	(No symbol) [0x00007FF740051E82]
	(No symbol) [0x00007FF74004122F]
	BaseThreadInitThunk [0x00007FFFD70C257D+29]
	RtlUserThreadStart [0x00007FFFD7FCAA58+40]



2024-06-25 19:32:39.565 | INFO | TestCase.conftest:add_report_requests:77 | 添加举报数据成功
2024-06-25 19:32:39.566 | INFO | Common.logger:wrapper:43 | 函数 test_boss_report_pass_notice 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x000001CA62042000>,){'add_report_requests': 126}
2024-06-25 19:32:44.708 | ERROR | Common.logger:wrapper:53 | 函数 test_boss_report_pass_notice 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_boss_report.py", line 145, in test_boss_report_pass_notice
    driver.switch_to.alert.accept()
    ^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\switch_to.py", line 58, in alert
    _ = alert.text
        ^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\common\alert.py", line 58, in text
    return self.driver.execute(Command.W3C_GET_ALERT_TEXT)["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoAlertPresentException: Message: no such alert
  (Session info: chrome=126.0.6478.115)
Stacktrace:
	GetHandleVerifier [0x00007FF7400D3E52+31618]
	(No symbol) [0x00007FF74004B0B9]
	(No symbol) [0x00007FF73FF086B9]
	(No symbol) [0x00007FF73FEF8237]
	(No symbol) [0x00007FF73FF2BEEF]
	(No symbol) [0x00007FF73FF7D1BD]
	(No symbol) [0x00007FF73FF2BD6B]
	(No symbol) [0x00007FF73FF7CEB3]
	(No symbol) [0x00007FF73FF4A46B]
	(No symbol) [0x00007FF73FF4B001]
	GetHandleVerifier [0x00007FF7403DA02D+3202397]
	GetHandleVerifier [0x00007FF740426A4D+3516285]
	GetHandleVerifier [0x00007FF74041C4C0+3473904]
	GetHandleVerifier [0x00007FF740185D56+760454]
	(No symbol) [0x00007FF740056B5F]
	(No symbol) [0x00007FF740051CF4]
	(No symbol) [0x00007FF740051E82]
	(No symbol) [0x00007FF74004122F]
	BaseThreadInitThunk [0x00007FFFD70C257D+29]
	RtlUserThreadStart [0x00007FFFD7FCAA58+40]



2024-06-25 19:37:18.076 | INFO | TestCase.conftest:add_report_requests:77 | 添加举报数据成功
2024-06-25 19:37:18.078 | INFO | Common.logger:wrapper:43 | 函数 test_boss_report_pass_notice 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x00000287F49B11C0>,){'add_report_requests': 127}
2024-06-25 19:37:25.541 | INFO | Common.logger:wrapper:48 | 函数 test_boss_report_pass_notice 执行完成，函数返回结果：None

2024-06-25 19:51:37.266 | INFO | TestCase.conftest:add_report_requests:77 | 添加举报数据成功
2024-06-25 19:51:37.267 | INFO | Common.logger:wrapper:43 | 函数 test_boss_report_pass_silence_hours 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x00000278DCF9FA10>,){'add_report_requests': 128}
2024-06-25 19:51:42.775 | INFO | TestCase.test_boss_report:test_boss_report_pass_silence_hours:322 | 审核状态：审核通过
2024-06-25 19:51:42.775 | INFO | TestCase.test_boss_report:test_boss_report_pass_silence_hours:325 | 违规原因：暴力恐怖
2024-06-25 19:51:42.939 | INFO | TestCase.test_boss_report:test_boss_report_pass_silence_hours:328 | 处理方式禁言10小时
2024-06-25 19:51:42.939 | INFO | TestCase.test_boss_report:test_boss_report_pass_silence_hours:331 | 备注
2024-06-25 19:51:42.939 | INFO | Common.logger:wrapper:48 | 函数 test_boss_report_pass_silence_hours 执行完成，函数返回结果：None

2024-06-25 19:57:21.436 | INFO | TestCase.conftest:add_report_requests:77 | 添加举报数据成功
2024-06-25 19:57:21.437 | INFO | Common.logger:wrapper:43 | 函数 test_boss_report_pass_silence_hours 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x000001E758210F50>,){'add_report_requests': 129}
2024-06-25 19:57:26.767 | ERROR | Common.logger:wrapper:53 | 函数 test_boss_report_pass_silence_hours 异常堆栈：Traceback (most recent call last):
  File "F:\python_project\appium_project\Common\logger.py", line 46, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\TestCase\test_boss_report.py", line 311, in test_boss_report_pass_silence_hours
    table = find_element_wrap(driver, 'xpath', '//*[@class="table table-hover grid-table"]/tbody')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\Common\find_element.py", line 10, in find_element_wrap
    raise e
  File "F:\python_project\appium_project\Common\find_element.py", line 7, in find_element_wrap
    element = WebDriverWait(driver, 10, 0.25).until(ec.visibility_of_element_located((find_type, find_key)))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 156, in _predicate
    return _element_if_visible(driver.find_element(*locator))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "F:\python_project\appium_project\.venv\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 228, in check_response
    raise exception_class(message, screen, stacktrace, alert_text)  # type: ignore[call-arg]  # mypy is not smart enough here
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
selenium.common.exceptions.UnexpectedAlertPresentException: Alert Text: 审核完成，请刷新数据
Message: unexpected alert open: {Alert text : 审核完成，请刷新数据}
  (Session info: chrome=126.0.6478.115)
Stacktrace:
	GetHandleVerifier [0x00007FF7400D3E52+31618]
	(No symbol) [0x00007FF74004B0B9]
	(No symbol) [0x00007FF73FF0888A]
	(No symbol) [0x00007FF73FF9D226]
	(No symbol) [0x00007FF73FF7CEB3]
	(No symbol) [0x00007FF73FF4A46B]
	(No symbol) [0x00007FF73FF4B001]
	GetHandleVerifier [0x00007FF7403DA02D+3202397]
	GetHandleVerifier [0x00007FF740426A4D+3516285]
	GetHandleVerifier [0x00007FF74041C4C0+3473904]
	GetHandleVerifier [0x00007FF740185D56+760454]
	(No symbol) [0x00007FF740056B5F]
	(No symbol) [0x00007FF740051CF4]
	(No symbol) [0x00007FF740051E82]
	(No symbol) [0x00007FF74004122F]
	BaseThreadInitThunk [0x00007FFFD70C257D+29]
	RtlUserThreadStart [0x00007FFFD7FCAA58+40]



2024-06-25 19:59:57.510 | INFO | TestCase.conftest:add_report_requests:77 | 添加举报数据成功
2024-06-25 19:59:57.511 | INFO | Common.logger:wrapper:43 | 函数 test_boss_report_pass_silence_hours 开始执行，入参:(<TestCase.test_boss_report.TestBossReport object at 0x00000259A1435370>,){'add_report_requests': 130}
2024-06-25 20:00:03.823 | INFO | TestCase.test_boss_report:test_boss_report_pass_silence_hours:326 | 审核状态：审核通过
2024-06-25 20:00:03.824 | INFO | TestCase.test_boss_report:test_boss_report_pass_silence_hours:329 | 违规原因：暴力恐怖
2024-06-25 20:00:03.991 | INFO | TestCase.test_boss_report:test_boss_report_pass_silence_hours:332 | 处理方式禁言1小时
2024-06-25 20:00:03.991 | INFO | TestCase.test_boss_report:test_boss_report_pass_silence_hours:335 | 备注
2024-06-25 20:00:03.992 | INFO | Common.logger:wrapper:48 | 函数 test_boss_report_pass_silence_hours 执行完成，函数返回结果：None

